package io.hpb.contract.entity;

import java.util.Date;

public class AuthRole extends io.hpb.contract.entity.BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.role_desc
     *
     * @mbg.generated
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.role_state
     *
     * @mbg.generated
     */
    private Integer roleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.create_at_time
     *
     * @mbg.generated
     */
    private Date createAtTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.id
     *
     * @return the value of auth_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.id
     *
     * @param id the value for auth_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.role_name
     *
     * @return the value of auth_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.role_name
     *
     * @param roleName the value for auth_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.role_desc
     *
     * @return the value of auth_role.role_desc
     *
     * @mbg.generated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.role_desc
     *
     * @param roleDesc the value for auth_role.role_desc
     *
     * @mbg.generated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.role_state
     *
     * @return the value of auth_role.role_state
     *
     * @mbg.generated
     */
    public Integer getRoleState() {
        return roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.role_state
     *
     * @param roleState the value for auth_role.role_state
     *
     * @mbg.generated
     */
    public void setRoleState(Integer roleState) {
        this.roleState = roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.create_at_time
     *
     * @return the value of auth_role.create_at_time
     *
     * @mbg.generated
     */
    public Date getCreateAtTime() {
        return createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.create_at_time
     *
     * @param createAtTime the value for auth_role.create_at_time
     *
     * @mbg.generated
     */
    public void setCreateAtTime(Date createAtTime) {
        this.createAtTime = createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthRole other = (AuthRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getRoleDesc() == null ? other.getRoleDesc() == null : this.getRoleDesc().equals(other.getRoleDesc()))
            && (this.getRoleState() == null ? other.getRoleState() == null : this.getRoleState().equals(other.getRoleState()))
            && (this.getCreateAtTime() == null ? other.getCreateAtTime() == null : this.getCreateAtTime().equals(other.getCreateAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getRoleDesc() == null) ? 0 : getRoleDesc().hashCode());
        result = prime * result + ((getRoleState() == null) ? 0 : getRoleState().hashCode());
        result = prime * result + ((getCreateAtTime() == null) ? 0 : getCreateAtTime().hashCode());
        return result;
    }
}