package io.hpb.contract.entity;

import java.util.Date;

public class AuthRoleResource extends io.hpb.contract.entity.BaseEntity<String,Object> {
    /**
	 * 
	 */
	private static final long serialVersionUID = 2535203543242977413L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_resource.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_resource.resource_id
     *
     * @mbg.generated
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_resource.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_resource.create_at_time
     *
     * @mbg.generated
     */
    private Date createAtTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_resource.id
     *
     * @return the value of auth_role_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_resource.id
     *
     * @param id the value for auth_role_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_resource.role_id
     *
     * @return the value of auth_role_resource.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_resource.role_id
     *
     * @param roleId the value for auth_role_resource.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_resource.resource_id
     *
     * @return the value of auth_role_resource.resource_id
     *
     * @mbg.generated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_resource.resource_id
     *
     * @param resourceId the value for auth_role_resource.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_resource.create_user_id
     *
     * @return the value of auth_role_resource.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_resource.create_user_id
     *
     * @param createUserId the value for auth_role_resource.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_resource.create_at_time
     *
     * @return the value of auth_role_resource.create_at_time
     *
     * @mbg.generated
     */
    public Date getCreateAtTime() {
        return createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_resource.create_at_time
     *
     * @param createAtTime the value for auth_role_resource.create_at_time
     *
     * @mbg.generated
     */
    public void setCreateAtTime(Date createAtTime) {
        this.createAtTime = createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthRoleResource other = (AuthRoleResource) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getResourceId() == null ? other.getResourceId() == null : this.getResourceId().equals(other.getResourceId()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateAtTime() == null ? other.getCreateAtTime() == null : this.getCreateAtTime().equals(other.getCreateAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getResourceId() == null) ? 0 : getResourceId().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateAtTime() == null) ? 0 : getCreateAtTime().hashCode());
        return result;
    }
}