package io.hpb.contract.entity;

import java.util.Date;

public class AuthUserRole extends io.hpb.contract.entity.BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.create_at_time
     *
     * @mbg.generated
     */
    private Date createAtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.id
     *
     * @return the value of auth_user_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.id
     *
     * @param id the value for auth_user_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.user_id
     *
     * @return the value of auth_user_role.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.user_id
     *
     * @param userId the value for auth_user_role.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.role_id
     *
     * @return the value of auth_user_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.role_id
     *
     * @param roleId the value for auth_user_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.create_at_time
     *
     * @return the value of auth_user_role.create_at_time
     *
     * @mbg.generated
     */
    public Date getCreateAtTime() {
        return createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.create_at_time
     *
     * @param createAtTime the value for auth_user_role.create_at_time
     *
     * @mbg.generated
     */
    public void setCreateAtTime(Date createAtTime) {
        this.createAtTime = createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.create_user_id
     *
     * @return the value of auth_user_role.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.create_user_id
     *
     * @param createUserId the value for auth_user_role.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthUserRole other = (AuthUserRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getCreateAtTime() == null ? other.getCreateAtTime() == null : this.getCreateAtTime().equals(other.getCreateAtTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getCreateAtTime() == null) ? 0 : getCreateAtTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        return result;
    }
}