package io.hpb.contract.entity;

import java.util.Date;

public class AuthUserSession extends io.hpb.contract.entity.BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.user_token
     *
     * @mbg.generated
     */
    private String userToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.organ_owner_id
     *
     * @mbg.generated
     */
    private String organOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.owner_id
     *
     * @mbg.generated
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.create_at_time
     *
     * @mbg.generated
     */
    private Date createAtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.keep_time
     *
     * @mbg.generated
     */
    private Integer keepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_session.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.user_token
     *
     * @return the value of auth_user_session.user_token
     *
     * @mbg.generated
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.user_token
     *
     * @param userToken the value for auth_user_session.user_token
     *
     * @mbg.generated
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken == null ? null : userToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.organ_owner_id
     *
     * @return the value of auth_user_session.organ_owner_id
     *
     * @mbg.generated
     */
    public String getOrganOwnerId() {
        return organOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.organ_owner_id
     *
     * @param organOwnerId the value for auth_user_session.organ_owner_id
     *
     * @mbg.generated
     */
    public void setOrganOwnerId(String organOwnerId) {
        this.organOwnerId = organOwnerId == null ? null : organOwnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.owner_id
     *
     * @return the value of auth_user_session.owner_id
     *
     * @mbg.generated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.owner_id
     *
     * @param ownerId the value for auth_user_session.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.create_at_time
     *
     * @return the value of auth_user_session.create_at_time
     *
     * @mbg.generated
     */
    public Date getCreateAtTime() {
        return createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.create_at_time
     *
     * @param createAtTime the value for auth_user_session.create_at_time
     *
     * @mbg.generated
     */
    public void setCreateAtTime(Date createAtTime) {
        this.createAtTime = createAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.keep_time
     *
     * @return the value of auth_user_session.keep_time
     *
     * @mbg.generated
     */
    public Integer getKeepTime() {
        return keepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.keep_time
     *
     * @param keepTime the value for auth_user_session.keep_time
     *
     * @mbg.generated
     */
    public void setKeepTime(Integer keepTime) {
        this.keepTime = keepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_session.end_time
     *
     * @return the value of auth_user_session.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_session.end_time
     *
     * @param endTime the value for auth_user_session.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthUserSession other = (AuthUserSession) that;
        return (this.getUserToken() == null ? other.getUserToken() == null : this.getUserToken().equals(other.getUserToken()))
            && (this.getOrganOwnerId() == null ? other.getOrganOwnerId() == null : this.getOrganOwnerId().equals(other.getOrganOwnerId()))
            && (this.getOwnerId() == null ? other.getOwnerId() == null : this.getOwnerId().equals(other.getOwnerId()))
            && (this.getCreateAtTime() == null ? other.getCreateAtTime() == null : this.getCreateAtTime().equals(other.getCreateAtTime()))
            && (this.getKeepTime() == null ? other.getKeepTime() == null : this.getKeepTime().equals(other.getKeepTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserToken() == null) ? 0 : getUserToken().hashCode());
        result = prime * result + ((getOrganOwnerId() == null) ? 0 : getOrganOwnerId().hashCode());
        result = prime * result + ((getOwnerId() == null) ? 0 : getOwnerId().hashCode());
        result = prime * result + ((getCreateAtTime() == null) ? 0 : getCreateAtTime().hashCode());
        result = prime * result + ((getKeepTime() == null) ? 0 : getKeepTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        return result;
    }
}