package io.hpb.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HpbVoteInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.coinbase
     *
     * @mbg.generated
     */
    private String coinbase;
    private Date createAtTime;

    public Date getCreateAtTime() {
		return createAtTime;
	}

	public void setCreateAtTime(Date createAtTime) {
		this.createAtTime = createAtTime;
	}


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.count
     *
     * @mbg.generated
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.operator_id
     *
     * @mbg.generated
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.cate
     *
     * @mbg.generated
     */
    private Integer cate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.link_url
     *
     * @mbg.generated
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_vote_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.id
     *
     * @return the value of hpb_vote_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.id
     *
     * @param id the value for hpb_vote_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.coinbase
     *
     * @return the value of hpb_vote_info.coinbase
     *
     * @mbg.generated
     */
    public String getCoinbase() {
        return coinbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.coinbase
     *
     * @param coinbase the value for hpb_vote_info.coinbase
     *
     * @mbg.generated
     */
    public void setCoinbase(String coinbase) {
        this.coinbase = coinbase == null ? null : coinbase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.name
     *
     * @return the value of hpb_vote_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.name
     *
     * @param name the value for hpb_vote_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.address
     *
     * @return the value of hpb_vote_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.address
     *
     * @param address the value for hpb_vote_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.count
     *
     * @return the value of hpb_vote_info.count
     *
     * @mbg.generated
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.count
     *
     * @param count the value for hpb_vote_info.count
     *
     * @mbg.generated
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.create_time
     *
     * @return the value of hpb_vote_info.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.create_time
     *
     * @param createTime the value for hpb_vote_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.update_time
     *
     * @return the value of hpb_vote_info.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.update_time
     *
     * @param updateTime the value for hpb_vote_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.operator_id
     *
     * @return the value of hpb_vote_info.operator_id
     *
     * @mbg.generated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.operator_id
     *
     * @param operatorId the value for hpb_vote_info.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.state
     *
     * @return the value of hpb_vote_info.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.state
     *
     * @param state the value for hpb_vote_info.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.cate
     *
     * @return the value of hpb_vote_info.cate
     *
     * @mbg.generated
     */
    public Integer getCate() {
        return cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.cate
     *
     * @param cate the value for hpb_vote_info.cate
     *
     * @mbg.generated
     */
    public void setCate(Integer cate) {
        this.cate = cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.link_url
     *
     * @return the value of hpb_vote_info.link_url
     *
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.link_url
     *
     * @param linkUrl the value for hpb_vote_info.link_url
     *
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_vote_info.description
     *
     * @return the value of hpb_vote_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_vote_info.description
     *
     * @param description the value for hpb_vote_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HpbVoteInfo other = (HpbVoteInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCoinbase() == null ? other.getCoinbase() == null : this.getCoinbase().equals(other.getCoinbase()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCate() == null ? other.getCate() == null : this.getCate().equals(other.getCate()))
            && (this.getLinkUrl() == null ? other.getLinkUrl() == null : this.getLinkUrl().equals(other.getLinkUrl()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCoinbase() == null) ? 0 : getCoinbase().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCate() == null) ? 0 : getCate().hashCode());
        result = prime * result + ((getLinkUrl() == null) ? 0 : getLinkUrl().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}