package io.hpb.contract.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuthUserSessionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public AuthUserSessionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserTokenIsNull() {
            addCriterion("user_token is null");
            return (Criteria) this;
        }

        public Criteria andUserTokenIsNotNull() {
            addCriterion("user_token is not null");
            return (Criteria) this;
        }

        public Criteria andUserTokenEqualTo(String value) {
            addCriterion("user_token =", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenNotEqualTo(String value) {
            addCriterion("user_token <>", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenGreaterThan(String value) {
            addCriterion("user_token >", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenGreaterThanOrEqualTo(String value) {
            addCriterion("user_token >=", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenLessThan(String value) {
            addCriterion("user_token <", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenLessThanOrEqualTo(String value) {
            addCriterion("user_token <=", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenLike(String value) {
            addCriterion("user_token like", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenNotLike(String value) {
            addCriterion("user_token not like", value, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenIn(List<String> values) {
            addCriterion("user_token in", values, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenNotIn(List<String> values) {
            addCriterion("user_token not in", values, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenBetween(String value1, String value2) {
            addCriterion("user_token between", value1, value2, "userToken");
            return (Criteria) this;
        }

        public Criteria andUserTokenNotBetween(String value1, String value2) {
            addCriterion("user_token not between", value1, value2, "userToken");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdIsNull() {
            addCriterion("organ_owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdIsNotNull() {
            addCriterion("organ_owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdEqualTo(String value) {
            addCriterion("organ_owner_id =", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdNotEqualTo(String value) {
            addCriterion("organ_owner_id <>", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdGreaterThan(String value) {
            addCriterion("organ_owner_id >", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("organ_owner_id >=", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdLessThan(String value) {
            addCriterion("organ_owner_id <", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("organ_owner_id <=", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdLike(String value) {
            addCriterion("organ_owner_id like", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdNotLike(String value) {
            addCriterion("organ_owner_id not like", value, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdIn(List<String> values) {
            addCriterion("organ_owner_id in", values, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdNotIn(List<String> values) {
            addCriterion("organ_owner_id not in", values, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdBetween(String value1, String value2) {
            addCriterion("organ_owner_id between", value1, value2, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOrganOwnerIdNotBetween(String value1, String value2) {
            addCriterion("organ_owner_id not between", value1, value2, "organOwnerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("owner_id like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("owner_id not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeIsNull() {
            addCriterion("create_at_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeIsNotNull() {
            addCriterion("create_at_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeEqualTo(Date value) {
            addCriterion("create_at_time =", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeNotEqualTo(Date value) {
            addCriterion("create_at_time <>", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeGreaterThan(Date value) {
            addCriterion("create_at_time >", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at_time >=", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeLessThan(Date value) {
            addCriterion("create_at_time <", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_at_time <=", value, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeIn(List<Date> values) {
            addCriterion("create_at_time in", values, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeNotIn(List<Date> values) {
            addCriterion("create_at_time not in", values, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeBetween(Date value1, Date value2) {
            addCriterion("create_at_time between", value1, value2, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_at_time not between", value1, value2, "createAtTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeIsNull() {
            addCriterion("keep_time is null");
            return (Criteria) this;
        }

        public Criteria andKeepTimeIsNotNull() {
            addCriterion("keep_time is not null");
            return (Criteria) this;
        }

        public Criteria andKeepTimeEqualTo(Integer value) {
            addCriterion("keep_time =", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeNotEqualTo(Integer value) {
            addCriterion("keep_time <>", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeGreaterThan(Integer value) {
            addCriterion("keep_time >", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("keep_time >=", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeLessThan(Integer value) {
            addCriterion("keep_time <", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeLessThanOrEqualTo(Integer value) {
            addCriterion("keep_time <=", value, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeIn(List<Integer> values) {
            addCriterion("keep_time in", values, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeNotIn(List<Integer> values) {
            addCriterion("keep_time not in", values, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeBetween(Integer value1, Integer value2) {
            addCriterion("keep_time between", value1, value2, "keepTime");
            return (Criteria) this;
        }

        public Criteria andKeepTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("keep_time not between", value1, value2, "keepTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_user_session
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_user_session
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}