package io.hpb.contract.mapper;

import io.hpb.contract.entity.AuthResource;
import io.hpb.contract.example.AuthResourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AuthResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    long countByExample(AuthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int deleteByExample(AuthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int insert(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int insertSelective(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    List<AuthResource> selectByExample(AuthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    AuthResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthResource record, @Param("example") AuthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthResource record, @Param("example") AuthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthResource record);
    
    List<AuthResource> selectByUserId(@Param("userId") Integer userId);

	List<AuthResource> selectByPage(Map<String, Object> map);

	Long count(Map<String, Object> map);

	int updateByCondition(Map<String, Object> map);

	int insertByCondition(Map<String, Object> map);

	List<AuthResource> selectAllResource();
	public List<AuthResource> selectAllCategory();//add by huangshuidan 2018-08-03
}