package io.hpb.contract.mapper;

import io.hpb.contract.entity.AuthRole;
import io.hpb.contract.example.AuthRoleExample;
import io.hpb.contract.vo.OwnerDetailInfoVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    long countByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int deleteByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int insert(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int insertSelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    List<AuthRole> selectByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    AuthRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthRole record, @Param("example") AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthRole record, @Param("example") AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthRole record);
    

	/**
	 * 分页查询角色信息
	 * @param map
	 * @return
	 */
	List<AuthRole> selectByPage(Map<String, Object> map);

	/**
	 * 统计条目数
	 * @param map
	 * @return
	 */
	Long count(Map<String, Object> map);

	int insertByCondition(Map<String, Object> map);

	int updateByCondition(Map<String, Object> map);
	
	/**
	 * 用户查询
	 * @param map
	 * @return
	 */
    List<OwnerDetailInfoVo> selectFullInfo(Map<String, Object> map);

	/**
	 * 保存并返回主键
	 * @param authRole
	 * @return
	 */
	int save(AuthRole authRole);
}