package io.hpb.contract.mapper;

import io.hpb.contract.entity.AuthRoleResource;
import io.hpb.contract.example.AuthRoleResourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    long countByExample(AuthRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int deleteByExample(AuthRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int insert(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int insertSelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    List<AuthRoleResource> selectByExample(AuthRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    AuthRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthRoleResource record, @Param("example") AuthRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthRoleResource record, @Param("example") AuthRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthRoleResource record);
}