package io.hpb.contract.mapper;

import io.hpb.contract.entity.AuthUser;
import io.hpb.contract.example.AuthUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    long countByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int deleteByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    List<AuthUser> selectByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    AuthUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthUser record);

    AuthUser selectByUsername(String username);

    List<AuthUser> selectByCondition(Map<String, Object> map);
}