package io.hpb.contract.mapper;

import io.hpb.contract.entity.AuthSession;
import io.hpb.contract.example.AuthSessionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    long countByExample(AuthSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int deleteByExample(AuthSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int insert(AuthSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int insertSelective(AuthSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    List<AuthSession> selectByExample(AuthSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    AuthSession selectByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthSession record, @Param("example") AuthSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthSession record, @Param("example") AuthSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthSession record);

    void init();
}