package io.hpb.contract.mapper;

import io.hpb.contract.entity.HpbVoteInfo;
import io.hpb.contract.example.HpbVoteInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HpbVoteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    long countByExample(HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int deleteByExample(HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int insert(HpbVoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int insertSelective(HpbVoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    List<HpbVoteInfo> selectByExampleWithBLOBs(HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    List<HpbVoteInfo> selectByExample(HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    HpbVoteInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbVoteInfo record, @Param("example") HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") HpbVoteInfo record, @Param("example") HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbVoteInfo record, @Param("example") HpbVoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpbVoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HpbVoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_vote_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpbVoteInfo record);
}